import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';

function RecommendationList({ recommendations, aiRecommendations }) {
  const [expandedSteps, setExpandedSteps] = useState({});

  const toggleSteps = (index) => {
    setExpandedSteps(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  const hasStandardRecs = recommendations && recommendations.length > 0;
  const hasAIRecs = aiRecommendations && aiRecommendations.length > 0;

  if (!hasStandardRecs && !hasAIRecs) {
    return <p style={{ color: 'var(--text-secondary)' }}>No recommendations yet</p>;
  }

  return (
    <div className="recommendations-container">
      {/* Standard Recommendations Section */}
      {hasStandardRecs && (
        <div className="recommendations-section">
          <h3 className="section-subtitle">📋 Action Plan</h3>
          {recommendations.map((rec, index) => (
            <div 
              key={index} 
              className={`recommendation-item priority-${rec.priority}`}
            >
              <div className="recommendation-header">
                <div className="recommendation-title">
                  {rec.title}
                  <span className={`priority-badge priority-${rec.priority}`}>
                    {rec.priority}
                  </span>
                </div>
              </div>
              <div className="recommendation-description">
                {rec.description}
              </div>
              
              {/* Action Steps */}
              {rec.action_steps && rec.action_steps.length > 0 && (
                <div className="action-steps-container">
                  <button 
                    className="action-steps-toggle"
                    onClick={() => toggleSteps(index)}
                  >
                    {expandedSteps[index] ? '▼' : '▶'} View Detailed Steps ({rec.action_steps.length})
                  </button>
                  
                  {expandedSteps[index] && (
                    <div className="action-steps-list">
                      {rec.action_steps.map((step, stepIdx) => (
                        <div key={stepIdx} className="action-step">
                          <div className="step-header">
                            <span className="step-number">Step {step.step}</span>
                            <span className="step-timeframe">{step.timeframe}</span>
                          </div>
                          <div className="step-action">{step.action}</div>
                          <div className="step-details">{step.details}</div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* AI Recommendations Section */}
      {hasAIRecs && (
        <div className="recommendations-section ai-recommendations">
          <h3 className="section-subtitle">🤖 AI Insights</h3>
          <p className="ai-recommendations-intro">
            Personalized recommendations generated by AI based on your visibility data:
          </p>
          {aiRecommendations.map((aiRec, index) => {
            // Get content and convert literal \n to actual newlines for markdown
            const rawContent = aiRec.content || aiRec.description || '';
            const markdownContent = rawContent.replace(/\\n/g, '\n');
            
            return (
              <div key={index} className="ai-recommendation-item">
                <div className="ai-provider-badge">
                  {aiRec.provider || aiRec.ai_provider || 'AI'}
                </div>
                <div className="ai-recommendation-content markdown-content">
                  <ReactMarkdown>{markdownContent}</ReactMarkdown>
                </div>
                {(aiRec.generatedAt || aiRec.created_at) && (
                  <div className="ai-generated-time">
                    Generated: {new Date(aiRec.generatedAt || aiRec.created_at).toLocaleString()}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

export default RecommendationList;
